version: '3'
networks:
  criticism:
        driver: bridge
services:
  db:
    image: postgres:10.0
    container_name: criticism_db
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./sqldata:/sqldata
    networks:
      criticism:
        aliases:
          - db
    environment:
      POSTGRES_DB: criticism
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - 6432:5432

  backend-api:
    image: registry.cn-hangzhou.aliyuncs.com/criticism/backend-api:latest
    container_name: criticism_backend-api
    restart: always
    ports:
      - 8085:8085
    volumes:
      - ./logs/backend:/logs
    networks:
      - criticism
    depends_on:
      - db
    environment:
      SB_ARGS: "-Dspring.profiles.active=dev \
      -Dspring.datasource.url=jdbc:postgresql://db:5432/criticism \
      -Dspring.datasource.username=postgres \
      -Dspring.jpa.hibernate.ddl-auto=update \
      -Dspring.datasource.password=1234 \
      "

